name: pa-predict
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - shap
  - matplotlib
  - seaborn
  - jinja2
  - joblib
  - scipy
  - pip
